LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := DuckDuckGo
LOCAL_SRC_FILES := priv-app/DuckDuckGo.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := Browser2
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
